#!/usr/bin/env bash

docker-machine start default
docker-compose up &

echo 'waiting for services to start'
sleep 10s

export VAULT_ADDR=http://192.168.99.100:8200
export VAULT_TOKEN=test
export ELASTIC_HOST=http://0.0.0.0:9200
#export ELASTIC_HOST=http://192.168.99.100:9200

docker exec test_vault_1 vault write secret/elastic/clusters\
    cluster_1=$ELASTIC_HOST\
    cluster_2=$ELASTIC_HOST

