#!/usr/bin/env bash

docker-machine start default
docker-compose up &

echo 'waiting for services to start'
sleep 10s

export VAULT_ADDR=http://192.168.99.100:8200
export VAULT_TOKEN=$TEST_VAULT_TOKEN

docker exec test_vault_1 vault write secret/elastic/clusters\
    cluster_1=secret/elastic/clusters/cluster_1\
    cluster_2=secret/elastic/clusters/cluster_2

docker exec test_vault_1 vault write secret/elastic/clusters/cluster_1\
    address=http://192.168.99.100:9200\
    name=none \
    password=none

docker exec test_vault_1 vault write secret/elastic/clusters/cluster_2\
    host=http://192.168.99.100:9200\
    name=none \
    password=none
