#!/usr/bin/env bash

docker-machine start default
docker-compose up &

echo 'waiting for services to start'
sleep 10s

export VAULT_ADDR=http://192.168.99.100:8200
export VAULT_TOKEN=$TEST_VAULT_TOKEN

docker exec test_vault_1 vault write secret/elastic\
    name=$ELASTIC \
    password=$ELASTIC

# TODO HSC: add more things into vault, but make vault optional...
# TODO HSC: give a list of vault paths, one for each cluster of the organisation, and load them automatically

# TODO HSC: add vault token and paths with a command for non-base organisations?